In [1]:
import numpy as np

In [2]:
#1
arr1=np.array([10,20,30,40,50])
print(arr1.shape, arr1.size, arr1.dtype)

(5,) 5 int64


In [3]:
#2
arr2=np.arange(1,13).reshape(3,4)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
#3
arr0=np.zeros(3)
arr1=np.ones(3)
arri=np.identity(3)
print(arr0)

print(arr1)

print(arri)

[0. 0. 0.]
[1. 1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
#4
arrayeven=np.arange(10,50,2)
arrayeven

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [6]:
#5
arrls=np.linspace(0,1,10)
arrls

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [7]:
#6
a=np.array([1,2,3,4,5,6])
b=np.array([7,8,9,10,11,12])

In [8]:
#7
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[ 8 10 12 14 16 18]
[-6 -6 -6 -6 -6 -6]
[ 7 16 27 40 55 72]
[0.14285714 0.25       0.33333333 0.4        0.45454545 0.5       ]


In [9]:
#8
print(a*1.15)

[1.15 2.3  3.45 4.6  5.75 6.9 ]


In [10]:
#9
print(np.maximum(a,b))
print(np.minimum(a,b))

[ 7  8  9 10 11 12]
[1 2 3 4 5 6]


In [11]:
#10
arr=np.arange(21)
print(arr[:5])
print(arr[-5:])
print(arr[5:16])
print(arr[1::2])

[0 1 2 3 4]
[16 17 18 19 20]
[ 5  6  7  8  9 10 11 12 13 14 15]
[ 1  3  5  7  9 11 13 15 17 19]


In [12]:
#11
arr=np.arange(10)
arr[:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [13]:
original = np.array([1, 2, 3, 4, 5])
view = original[1:4]
copy = original[1:4].copy()

In [14]:
#13
arr = np.array([1, 2, 3, 4, 5])
print(arr)
arrr=arr[::-1]
print(arrr)

[1 2 3 4 5]
[5 4 3 2 1]


In [15]:
#14
arr3d= np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr3d)
print(arr3d[1, 2])
print(arr3d[1, 1])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
60
50


In [16]:
#15
subarr3d=arr3d[:2, 1:]
print(subarr3d)

[[20 30]
 [50 60]]


In [17]:
#16
arrm = np.arange(1, 26).reshape(5, 5)
print(arrm[0, :])
print(arrm[:, -1])
print(arrm[2, 2])
print(arrm[:3, :3])

[1 2 3 4 5]
[ 5 10 15 20 25]
13
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [18]:
#17
arr=np.arange(1,13).reshape(3,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
#18
arr=np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
#19
arr_3d = np.arange(18).reshape(2, 3, 3)
print("og_array",arr_3d)
transpose=arr_3d.transpose()
print("transposed",transpose)

og_array [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
transposed [[[ 0  9]
  [ 3 12]
  [ 6 15]]

 [[ 1 10]
  [ 4 13]
  [ 7 16]]

 [[ 2 11]
  [ 5 14]
  [ 8 17]]]


In [31]:
#20
arr_3d=np.arange(18).reshape(2,3,3)
print("orginal",arr_3d)

swap = arr_3d.swapaxes(0, 2)
print("swapped",swap)

og_array [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
swapped [[[ 0  9]
  [ 3 12]
  [ 6 15]]

 [[ 1 10]
  [ 4 13]
  [ 7 16]]

 [[ 2 11]
  [ 5 14]
  [ 8 17]]]


In [35]:
#21
A=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B=np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

add=A+B
print("addition",add)
mul=A*B
print("multiply",mul)

addition [[10 10 10]
 [10 10 10]
 [10 10 10]]
multiply [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [36]:
prod=np.dot(A, B)
prod

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [39]:
Tr=A.T
original=np.dot(Tr, A)
original

array([[ 66,  78,  90],
       [ 78,  93, 108],
       [ 90, 108, 126]])

In [40]:
arr=np.array([4, 9, 16, 25, 36])
root=np.sqrt(arr)
root

array([2., 3., 4., 5., 6.])

In [41]:
arr=np.array([0, 1, 2, 3])
exponent=np.exp(arr)
exponent

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [45]:
arr=np.random.randn(5)
sq=np.sqrt(np.abs(arr))
exp=np.exp(arr)
abs=np.abs(arr)
print("Sqrt (of abs):", sq)
print("Exp:", exp)
print("Abs:", abs)

Sqrt (of abs): [0.75589693 0.96129227 1.61633815 0.97486906 0.90357351]
Exp: [0.56474546 0.39689527 0.07334734 2.58666573 2.26244272]
Abs: [0.57138017 0.92408284 2.61254901 0.95036968 0.81644508]


In [52]:
arr1 = np.random.randint(0, 10, size=5)
arr2 = np.random.randint(0, 10, size=5)
max = np.maximum(arr1, arr2)
max

array([5, 5, 9, 9, 9])

In [53]:
marks = np.array([35, 72, 48, 90, 55, 28])
new_marks = np.where(marks < 40, 0, marks)
new_marks

array([ 0, 72, 48, 90, 55,  0])

In [56]:
income = np.array([45000, 62000, 38000, 75000, 50000, 29000])
classify = np.where(income >= 50000, 'high', 'low')
classify

array(['low', 'high', 'low', 'high', 'high', 'low'], dtype='<U4')

In [58]:
arr = np.array([10, 25, 30, 35, 50, 80])
arr_mod = np.where(arr > 30, 100, arr)
arr_mod

array([ 10,  25,  30, 100, 100, 100])

In [62]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

s = np.sum(mat)
print(s)
m = np.mean(mat)
print(m)
v = np.var(mat)
print(v)
dev = np.std(mat)
print(dev)

45
5.0
6.666666666666667
2.581988897471611


In [64]:
row = np.sum(mat, axis=1)
col = np.sum(mat, axis=0)

In [66]:
marks = np.array([72, 85, 63, 91, 78, 54, 88, 95, 67, 82])
mean_m = np.mean(marks)
print(mean_m)
std_m = np.std(marks)
print(std_m)
min_m = np.min(marks)
print(min_m)
max_m = np.max(marks)
print(max_m)

77.5
12.56383699353028
54
95


In [69]:
boolean = np.array([True, False, True, True, False])
any = np.any(boolean)
print(any)
all = np.all(boolean)
print(all)

True
False


In [71]:
arr = np.random.randint(1, 100, size=10)
sorted = np.sort(arr)
sorted

array([24, 26, 29, 41, 53, 60, 80, 82, 85, 89])

In [72]:
arr = np.array([1, 2, 3, 2, 4, 5, 3, 6, 4, 7, 8, 5])
unq = np.unique(arr)
unq

array([1, 2, 3, 4, 5, 6, 7, 8])

In [73]:
mark = np.array([85, 92, 78, 92, 85, 67, 78, 90, 85, 73])
unq_mark = np.unique(mark)
unq_mark

array([67, 73, 78, 85, 90, 92])

In [75]:
arr = np.array([10, 20, 30, 40, 50, 60])
search = np.array([20, 35, 50, 70])
search

array([20, 35, 50, 70])

In [77]:
inside = np.isin(search, arr)
inside

array([ True, False,  True, False])